blog/urls.py
from django.urls import path
from .views import HomeView, BlogListView, BlogDetailView, BlogSearchView
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('blog/<str:cat_name>/', BlogListView.as_view(), name='blog_list_category'),
    path('blog/<str:username>/', BlogListView.as_view(), name='blog_list_author'),
    path('blog/tag/<str:tag_name>/', BlogListView.as_view(), name='tag'),

    # Define URL pattern for the blog detail page with post ID parameter
    path('<int:pk>/', BlogDetailView.as_view(), name='single'),

    # Define URL pattern for the blog search page
    path('search/', BlogSearchView.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog":BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.handler404'

services/urls.py
from django.urls import path
from .views import *

app_name = 'services'

urlpatterns = [
    path('', ServicesListView.as_view(), name='index'),
    path('<int:pk>/', ServicesDetailView.as_view(), name='single'),
    path('search/', ServicesSearchView.as_view(), name='search'),


]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contactus/', ContactUsView.as_view(), name='contactus'),
    path('newslettersignup/', NewsletterView.as_view(), name='newsletter'),
    path('search/', IndexSearchView.as_view(), name='search'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django_jalali.db import models as jmodels
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField("نام", max_length=31)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

class Post(models.Model):
    title = models.CharField("عنوان", max_length=255)
    content = RichTextField("محتوا")
    tags = TaggableManager("برچسب‌ها")
    published_date = jmodels.jDateField("تاریخ انتشار", null=True)
    status = models.BooleanField("نمایش در سایت", default=True)
    created_date = jmodels.jDateField("تاریخ ایجاد", auto_now_add=True)
    updated_date = jmodels.jDateField("تاریخ بروزرسانی", auto_now=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="نویسنده")
    counted_views = models.IntegerField("تعداد بازدیدها", default=0)
    counted_comment = models.IntegerField("تعداد نظرات", default=0)
    category = models.ManyToManyField(Category, verbose_name="دسته‌بندی")
    image = models.ImageField("تصویر", upload_to='post_images/') 

    class Meta:
        ordering = ['-created_date']
        verbose_name = "پست"
        verbose_name_plural = "پست‌ها"

    def __str__(self):
        return "{}-{}".format(self.title, self.id)
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="پست")
    name = models.CharField("نام", max_length=100)
    email = models.EmailField("ایمیل")
    phone_number = models.CharField("شماره تلفن", max_length=200)
    message = models.TextField("پیام")
    approved = models.BooleanField("تایید شده", default=False)
    created_date = models.DateTimeField("تاریخ ایجاد", auto_now_add=True)
    updated_date = models.DateTimeField("تاریخ بروزرسانی", auto_now=True)

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"

    def __str__(self):
        return f'{self.name} - {self.phone_number}'

website/models.py
from django.db import models

class WorkingHour(models.Model):
    DAY_CHOICES = (
        ('Sat', 'شنبه'),
        ('Sun', 'یکشنبه'),
        ('Mon', 'دوشنبه'),
        ('Tue', 'سه شنبه'),
        ('Wed', 'چهار شنبه'),
        ('Thu', 'پنج شنبه'),
        ('Fri', 'جمعه'),
    )

    start_day = models.CharField(max_length=3, choices=DAY_CHOICES, verbose_name="روز شروع")
    end_day = models.CharField(max_length=3, choices=DAY_CHOICES, verbose_name="روز پایان")
    start_time = models.CharField(max_length=256, verbose_name="زمان شروع")
    end_time = models.CharField(max_length=256, verbose_name="زمان پایان")

    class Meta:
        verbose_name = "ساعات کاری"
        verbose_name_plural = "ساعات کاری"

    def __str__(self):
        start_day_text = dict(self.DAY_CHOICES).get(self.start_day, '')
        end_day_text = dict(self.DAY_CHOICES).get(self.end_day, '')
        return f"{start_day_text} تا {end_day_text} {self.start_time}  الی {self.end_time} "

class Contact(models.Model):
    address = models.CharField(max_length=255, verbose_name="آدرس")
    mobile_phone = models.CharField(max_length=15, verbose_name="تلفن همراه")
    landline_phone = models.CharField(max_length=15, verbose_name="تلفن ثابت")
    email = models.EmailField(verbose_name="ایمیل")
    instagram = models.CharField(max_length=255, verbose_name="instagram ID", blank=True, null=True)
    whatsapp = models.CharField(max_length=255, verbose_name="whatsapp ", blank=True, null=True)
    workingHour = models.ForeignKey(WorkingHour, on_delete=models.CASCADE, blank=True, null=True, verbose_name="ساعت کاری")

    class Meta:
        verbose_name = "اطلاعات تماس"
        verbose_name_plural = "اطلاعات تماس"

    def __str__(self):
        return self.email
    
class ContactUs(models.Model):
    name = models.CharField(max_length=255, verbose_name="نام")
    email = models.EmailField(verbose_name="ایمیل")
    phone = models.CharField(max_length=15, verbose_name="تلفن")
    message = models.TextField(verbose_name="پیام")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")
    updated_date = models.DateTimeField(auto_now=True, verbose_name="تاریخ به روزرسانی")

    class Meta:
        ordering = ('created_date',)
        verbose_name = "پیام"
        verbose_name_plural = "پیام ها"

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    email=models.EmailField(verbose_name="ایمیل")

    class Meta:
        verbose_name = "خبرنامه"
        verbose_name_plural = "خبرنامه‌ها"

    def __str__(self):
        return self.email



class HomePage(models.Model):
    title = models.CharField(max_length=255, verbose_name="تیتر صفحه اصلی")
    top_text = models.TextField(verbose_name="متن بالای صفحه")
    banner = models.ImageField(upload_to='banners/', verbose_name="بنر صفحه اصلی")
    aboutـtitle = models.CharField(max_length=255, verbose_name="تیتر  درباره ما صفحه اصلی")
    about_text = models.TextField(verbose_name=" متن درباره صفحه اصلی" )
    aboutـbanner = models.ImageField(upload_to='banners/', verbose_name=" بنر در باره ما صفحه اصلی")
    bottom_text = models.TextField(verbose_name="متن پایین صفحه")

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "صفحه اصلی"
        verbose_name_plural = "صفحه اصلی"


class AboutUs(models.Model):
    title = models.CharField(max_length=255, verbose_name='عنوان')
    aboutuspage_image = models.ImageField(upload_to='aboutus/', verbose_name='تصویر صفحه درباره ما ', blank=True, null=True)
    content = models.TextField(verbose_name='محتوا')

    def __str__(self):
        return f"About Us - {self.title}"

    class Meta:
        verbose_name = 'درباره ما'
        verbose_name_plural = 'صفحه درباره ما'

website/forms.py
from django import forms
from .models import ContactUs,Newsletter

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'phone', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
        }


class NewsletterForm(forms.ModelForm):
    class Meta:
        model=Newsletter
        fields='__all__'

website/views.py
from django.shortcuts import render
from django.conf.urls import handler404
from django.views import View
from django.views.generic import ListView
from .models import Contact,HomePage ,AboutUs
from django.views.generic.edit import FormView
from .forms import ContactUsForm,NewsletterForm
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q
from itertools import chain
from blog.models import Post
from services.models import Services
from .query_manager import SearchQueryManager

class HomeView(View):
    template_name = 'website/index.html'

    def get(self, request):
        home_page = HomePage.objects.first()
        return render(request, self.template_name, {'home': home_page})

class AboutView(View):
    template_name = 'website/about.html'

    def get(self, request):
        about_us_data = AboutUs.objects.all()
        context = {'about': about_us_data}
        return render(request, self.template_name, context)
    
class ContactView(View):
    template_name = 'website/contact.html'

    def get(self, request):
        return render(request, self.template_name)

class ContactUsView(FormView):
    template_name = 'website/contact.html'
    form_class = ContactUsForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'پیام شما به موفقیت ارسال شد')
        return self.render_to_response(self.get_context_data(form=form, success=True))

    def form_invalid(self, form):
        messages.error(self.request, 'در پردازش درخواست شما خطایی رخ داده است. لطفاً دوباره امتحان کنید')
        return self.render_to_response(self.get_context_data(form=form, success=False))

class BaseView(ListView):
    model = Contact
    template_name = 'base.html'
    context_object_name = 'contacts'

class NewsletterView(FormView):
    template_name = 'website/index.html'
    form_class = NewsletterForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'ایمیل شما با موفقیت ثبت شد')
        return self.render_to_response(self.get_context_data(form=form, success=True))

    def form_invalid(self, form):
        messages.warning(self.request, 'لطفا ایمیل خود را به درستی وارد نمایید')
        return self.render_to_response(self.get_context_data(form=form, success=False))

class IndexSearchView(ListView):
    template_name = 'website/search-home.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('s')
        if query:
            posts = SearchQueryManager.search_posts(query)
            services = SearchQueryManager.search_services(query)
        else:
            posts, services = SearchQueryManager.get_all_posts_and_services()

        return posts, services

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('s', '')
        posts, services = self.get_queryset()
        context['post_list'] = posts
        context['service_list'] = services
        return context

templates/website/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% load main_tags %}

{% get_single_contact as contact %}


<div class="uni-banner">
<div class="container">
<div class="uni-banner-text">
<h1>تماس با ما</h1>
<ul>
<li><a href="{% url 'website:index' %}">خانه</a></li>
<li>تماس با ما</li>
</ul>
</div>
</div>
</div>


<div class="contact-page ptb-100">
<div class="container">
<div class="default-section-title">
<h6>ارسال پیام</h6>
</div>
<div class="section-content">
<div class="row">
<div class="col-lg-4 col-md-12 col-sm-12 col-12">
<div class="contact-card-area">
<div class="row justify-content-center">
<div class="col-lg-12 col-md-6 col-sm-12 col-12">
<div class="contact-card">
<i class="fas fa-map-marker-alt"></i>
<h4>موقعیت ما</h4>
<p>{{ contact.address }}</p>
</div>
</div>
<div class="col-lg-12 col-md-6 col-sm-12 col-12">
<div class="contact-card">
<i class="fas fa-phone-alt"></i>
<h4>تلفن ما</h4>
<p><a href="tel:{{ contact.mobile_phone }}">{{ contact.mobile_phone }}</a></p>
<p><a href="tel:{{ contact.landline_phone }}">{{ contact.landline_phone }}</a></p>
</div>
</div>
<div class="col-lg-12 col-md-6 col-sm-12 col-12">
<div class="contact-card">
<i class="far fa-envelope"></i>
<h4>ایمیل</h4>
<p><a href="mailto: {{ contact.email }}">{{ contact.email }}</a></p>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-8 col-md-12 col-sm-12 col-12">
<div class="contact-page-form-area">
<div class="bd-form details-text-area" id="bd-form">
<h3>ارسال پیام</h3>
<form action="{% url 'website:contactus' %}" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <input type="text" class="form-control" placeholder="نام" name="name" required>
      </div>
      <div class="col-md-6">
        <input type="email" class="form-control" placeholder="ایمیل" name="email" required>
      </div>
      <div class="col-md-6">
        <input type="text" class="form-control" placeholder="تلفن" name="phone" required>
      </div>
      <!-- <div class="col-md-6">
        <input type="text" class="form-control" placeholder="وبسایت" name="website" required>
      </div> -->
      <div class="col-md-12">
        <textarea rows="5" class="form-control" placeholder="پیام شما" name="message" required></textarea>
      </div>
      <div class="col-md-12">
        <button class="default-button" type="submit"><span>ارسال پیام</span></button>
      </div>
    </div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<!-- <div class="google-map">
<iframe class="g-map" src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2371.0813443498755!2d-113.4208817841543!3d53.53846178001977!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s25%2F50%20Street%20Here%20United%20For%20Australia!5e0!3m2!1sen!2sbd!4v1626086534014!5m2!1sen!2sbd"></iframe>
</div> -->
{% endblock content %}

templates/website/error404.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="error ptb-100">
<div class="container">
<div class="row justify-content-center text-center">
<div class="col-md-8">
<div class="default-section-title default-section-title-middle">
<h6>خطا 404</h6>
<h3>صفحه یافت نشد!</h3>
</div>
<div class="error-content">
<h1>404</h1>
<p>با عرض پوزش، صفحه مورد نظر شما هنوز وجود ندارد.</p>
<a class="default-button" href="{% url 'website:index' %}"><span>بازگشت به خانه</span></a>
</div>
</div>
</div>
</div>
</div>

{% endblock content %}

templates/website/index-services.html
{% load static %}
<div class="service ptb-100 bg-f9faff">
    <div class="container">
    <div class="default-section-title default-section-title-middle">
    <h6>خدمات ما</h6>
    <h3>ما بهترین خدمات را ارائه می دهیم</h3>
    </div>
    <div class="section-content">
    <div class="row">
    {% for post in posts|slice:":3" %}
    <div class="col-lg-4 col-md-6 col-sm-12 col-12">
    <div class="service-card-3">
    <div class="service-card-img-3">
    <img src="{{post.image.url}}" alt="{{post.title}}">
    </div>
    <div class="service-card-text-3">
    <h4><a href="{% url 'services:single' pk=post.id %}">{{post.title}}</a></h4>
    <p>{{ post.content|truncatewords:39|safe }}</p>
    <a class="read-more-btn" href="{% url 'services:single' pk=post.id %}">بیشتر بدانید</a>
    </div>
    </div>
    </div>
    {% endfor %}
    </div>
    </div>
    </div>
    </div>
    

templates/website/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% load main_tags %}

<!-- -------------------base----------------- -->

<div class="main-banner banner bg-f9faff">
<div class="shape">
<img class="black-line" src="{% static 'assets/images/banner/box-shape1.png' %}" alt="shape">
<img class="orange-line" src="{% static 'assets/images/banner/box-shape2.png' %}" alt="shape">
<img class="half-circle" src="{% static 'assets/images/banner/half-circle.png' %}" alt="shape">
</div>
<div class="container-fluid">
<div class="row align-items-center">
<div class="col-lg-7">
<div class="banner-text-area banner-text-area-3">
<h6>به دوستان تهویه خوش آمدید !</h6>
<h1>{{home.title}}</h1>
<p>{{home.top_text|safe|truncatechars:600}}</p>    
<a class="default-button default-button-4" href="{% url 'services:index' %}"><span>خدمات ما</span></a>
</div>
</div>
<div class="col-lg-5">
<div class="banner-img-area">
<img class="main-img" src="{{home.banner.url}}" alt="image">
<div class="shapes">
<img class="b3-dot" src="{% static 'assets/images/banner/b3-dots.png' %}" alt="shape">
<img class="dot-circle" src="{% static 'assets/images/banner/dot-circle.png' %}" alt="shape">
</div>
</div>
</div>
</div>
</div>
</div>

<div class="about about-1 pt-100">
<div class="container-fluid">
 <div class="row">
<div class="col-lg-6 col-md-12 col-sm-12 col-12">
<div class="about-img-area-3" style='background-image: url("{{home.aboutـbanner.url}}")'>
<!-- <div class="about-img-list">
<ul>
<li><strong>%100</strong> شرکت مورد اعتماد</li>
<li><strong>460</strong> پروژه تکمیل شده</li>
<li><strong>60</strong> برنده جایزه</li>
<li><strong>200</strong> رضایت مشتریان</li>
</ul>
</div> -->
</div>
</div>
<div class="col-lg-6 col-md-12 col-sm-12 col-12">
<div class="about-text-area pl-20">
<div class="default-section-title">
<h6> درباره ما </h6>
<h3>{{home.aboutـtitle}}</h3>
</div>
<p>{{home.about_text|safe|truncatechars:1100}}</p>
<a class="default-button default-button-4" href="{% url 'website:about' %}"><span>اطلاعات بیشتر</span></a>
</div>
</div>
</div>
</div>
</div>

<!-- 
<div class="features pt-70 pb-100">
<div class="container">
<div class="row justify-content-center">
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="features-card-3">
<i class="flaticon-customer-support"></i>
<h4>ارسال یک پیام</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="features-card-3">
<i class="flaticon-appointment"></i>
<h4>برنامه نظافت</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="features-card-3">
<i class="flaticon-support-1"></i>
<h4>ارائه خدمات</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
</div>
</div>
</div> -->

<!-- ---------------/ -->
<!-- service -->
<!-- {% include 'website/index-services.html' %} -->
{% display_latest_services %}


<!-- ---------------/ -->

<!-- <div class="why-we ptb-100">
<div class="container">
<div class="default-section-title default-section-title-middle">
<h6>چرا ما را انتخاب می کنید</h6>
<h3>چرا مشتریان ما را انتخاب می کنند</h3>
</div>
<div class="section-content">
<div class="row">
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="why-we-card-3">
<i class="flaticon-technical-support"></i>
<h4>تیم با تجربه</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="why-we-card-3">
<i class="flaticon-clock"></i>
<h4>خدمات سریع</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="why-we-card-3">
<i class="flaticon-review"></i>
<h4>بهترین تجهیزات</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="why-we-card-3">
<i class="flaticon-leaf"></i>
<h4>محصولات طبیعی</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="why-we-card-3">
<i class="flaticon-booking"></i>
<h4>رزرو آنلاین آسان</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-6 col-12">
<div class="why-we-card-3">
<i class="flaticon-user"></i>
<h4>بیمه شده و محدود</h4>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
</div>
</div>
</div>
</div>
</div>
</div> -->

<!-- 
<div class="booking booking-3">
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6">
<div class="booking-form-area booking-form-area-3">
<div class="booking-form-content-3">
<div class="default-section-title default-section-title-middle">
<h3>درخواست خدمات</h3>
</div>
<form>
<div class="row">
<div class="col-lg-6 col-md-6 col-sm-6 col-12">
<div class="booking-form-content">
<input type="text" class="form-control" placeholder="نام">
</div>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-12">
<div class="booking-form-content">
<input type="Email" class="form-control" placeholder="ایمیل">
</div>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-12">
<div class="booking-form-content">
<input type="text" class="form-control" placeholder="کد پستی">
</div>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-12">
<div class="booking-form-content">
<input type="text" class="form-control" placeholder="تلفن">
</div>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-12">
<div class="booking-form-content">
<select class="form-select" aria-label="Default select example">
<option selected disabled>انتخاب خدمات</option>
<option value="1">نظافت اتاق خواب</option>
<option value="2">نظافت دفتر کار</option>
<option value="3">نظافت خانه</option>
</select>
</div>
</div>
<div class="col-lg-6 col-md-6 col-sm-6 col-12">
<div class="booking-form-content">
<button class="default-button" type="submit"><span>ارسال جزئیات</span></button>
</div>
</div>
 </div>
</form>
</div>
</div>
</div>
<div class="col-lg-6">
<div class="booking-play-button">
<div class="play-button">
<a class="video-popup" href="https://www.youtube.com/watch?v=0qNsC-NLuhM"><i class="flaticon-play-button"></i></a>
</div>
</div>
</div>
</div>
</div>
</div>
 -->
<!-- 
<div class="testimonial ptb-100">
<div class="container">
<div class="default-section-title default-section-title-middle">
<h6>بازخورد مشتریان</h6>
<h3>مشتریان درباره ما چه می گویند</h3>
</div>
<div class="section-content">
<div class="row justify-content-center">
<div class="col-lg-4 col-md-6 col-sm-12 col-12">
<div class="testimonial-card testimonial-card-3">
<i class="flaticon-right-quote"></i>
<div class="testimonial-footer">
<img src="{% static 'assets/images/testimonial/tc1.jpg' %}" alt="image">
<div class="testimonial-footer-intro">
<h4>جان اسمیت</h4>
<p>طراح وب</p>
</div>
</div>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
<div class="stars">
<ul>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="far fa-star"></i></li>
<li><span>4.0</span></li>
</ul>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-12 col-12">
<div class="testimonial-card testimonial-card-3">
<i class="flaticon-right-quote"></i>
<div class="testimonial-footer">
<img src="{% static 'assets/images/testimonial/tc2.jpg' %}" alt="image">
<div class="testimonial-footer-intro">
<h4>سن واتسون</h4>
<p>طراح وب</p>
</div>
</div>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
<div class="stars">
<ul>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><span>5.0</span></li>
</ul>
 </div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-12 col-12">
<div class="testimonial-card testimonial-card-3">
<i class="flaticon-right-quote"></i>
<div class="testimonial-footer">
<img src="{% static 'assets/images/testimonial/tc3.jpg' %}" alt="image">
<div class="testimonial-footer-intro">
<h4>الکس آلینا</h4>
<p>طراح وب</p>
</div>
</div>
<p>لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم به سادگی ساختار چاپ و متن را در بر می گیرد. لورم ایپسوم استاندارد صنعت بوده است.</p>
<div class="stars">
<ul>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="fas fa-star"></i></li>
<li><i class="far fa-star"></i></li>
<li><span>4.0</span></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</div> -->

{% display_latest_posts %}



<!-- _____________footer__________________ -->
{% endblock content %}