blog/urls.py
from django.urls import path
from .views import HomeView, BlogListView, BlogDetailView, BlogSearchView
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('blog/<str:cat_name>/', BlogListView.as_view(), name='blog_list_category'),
    path('blog/<str:username>/', BlogListView.as_view(), name='blog_list_author'),
    path('blog/tag/<str:tag_name>/', BlogListView.as_view(), name='tag'),

    # Define URL pattern for the blog detail page with post ID parameter
    path('<int:pk>/', BlogDetailView.as_view(), name='single'),

    # Define URL pattern for the blog search page
    path('search/', BlogSearchView.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog":BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.handler404'

services/urls.py
from django.urls import path
from .views import *

app_name = 'services'

urlpatterns = [
    path('', ServicesListView.as_view(), name='index'),
    path('<int:pk>/', ServicesDetailView.as_view(), name='single'),
    path('search/', ServicesSearchView.as_view(), name='search'),


]

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contactus/', ContactUsView.as_view(), name='contactus'),
    path('newslettersignup/', NewsletterView.as_view(), name='newsletter'),
    path('search/', IndexSearchView.as_view(), name='search'),

]

services/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField("نام", max_length=31)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

class Services(models.Model):
    title = models.CharField("عنوان", max_length=255)
    content = RichTextField("محتوا")
    status = models.BooleanField("وضعیت", default=False)
    published_date = models.DateTimeField("تاریخ انتشار", null=True,auto_now_add=True)
    created_date = models.DateTimeField("تاریخ ایجاد", auto_now_add=True)
    updated_date = models.DateTimeField("تاریخ بروزرسانی", auto_now=True)
    category = models.ManyToManyField(Category, verbose_name="دسته‌بندی")
    image = models.ImageField("تصویر", upload_to='services_images/') 

    class Meta:
        ordering = ['-created_date']
        verbose_name = "خدمات"
        verbose_name_plural = "خدمات"

    def __str__(self):
        return "{}-{}".format(self.title, self.id)

services/views.py
from django.shortcuts import render
from django.views import View
from django.utils import timezone
from django.views.generic import ListView
from .models import *
from django.views.generic import DetailView
from .query_manager import ServicesQueryManager


class ServicesListView(ListView):
    model = Services
    template_name = 'services/services_home.html'
    context_object_name = 'services'
    paginate_by = 6

    def get_queryset(self):
        cat_name = self.kwargs.get('cat_name')
        username = self.kwargs.get('username')
        tag_name = self.kwargs.get('tag_name')

        queryset = ServicesQueryManager.get_all_services(cat_name, username, tag_name)

        return queryset

class ServicesDetailView(DetailView):
    model = Services
    template_name = 'services/service-single.html'
    context_object_name = 'post'


class ServicesSearchView(ListView):
    template_name = 'services/services_home.html'
    context_object_name = 'services'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('s')  # Retrieve the 's' parameter from the GET request

        if query:
            queryset = ServicesQueryManager.search_services(query)
        else:
            queryset = ServicesQueryManager.get_all_services()

        return queryset

templates/services/service-search.html
<div class="sidebar-card search-box">
    <form action="{% url 'services:search' %}">
    <div class="input-group">
    <!-- <input type="text" class="form-control" placeholder="جستجو..." required> -->
    <input type="text" class="form-control" name="s" placeholder="جستجو..." required>
    <button class="btn" type="submit"><i class="fas fa-search"></i></button>
    </div>
    </form>
    </div>

templates/services/service-single.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load static %}

{% block content %}
<div class="uni-banner">
<div class="container">
<div class="uni-banner-text">
<h1>{{post.title}}</h1>
<ul>
<li><a href="{% url 'website:index' %}">خانه</a></li>
<li>جزئیات خدمات</li>
</ul>
</div>
</div>
</div>


<div class="service detials-page ptb-100">
<div class="container">
<div class="row">
<div class="col-lg-8 col-md-12 col-sm-12 col-12">
<div class="details-text-area pr-20">
<div class="details-page-img">
<img src="{{ post.image.url }}" alt="image">
</div>
<h3>{{post.title}}</h3>
<p>{{post.content|safe}}</p>
</div>
</div>
<div class="col-lg-4 col-md-12 col-sm-12 col-12">
<div class="sidebar-content pt-30">
{% include 'services/service-search.html' %}
{% postcategories %}
{% include 'blog/blog-hours.html' %}
</div>
</div>
</div>
</div>
</div>


{% endblock content %}

templates/services/services_home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="uni-banner">
<div class="container">
<div class="uni-banner-text">
<h1>خدمات </h1>
<ul>
<li><a href="{% url 'website:index' %}">خانه</a></li>
<li>خدمات</li>
</ul>
</div>
</div>
</div>


<div class="service service-4 ptb-100">
<div class="container">
<div class="default-section-title default-section-title-middle">
<h6>خدمات ما</h6>
<h3>ما بهترین خدمات را ارائه می دهیم</h3>
</div>
<div class="section-content row">
{% for post in services %}
<div class="col-lg-4 col-md-6 col-sm-12 col-12">
<div class="service-card-3">
<div class="service-card-img-3">
<a href="{% url 'services:single' pk=post.id %}">
<img src="{{ post.image.url }}"  alt="{{ post.title }}">
</a>
</div>
<div class="service-card-text-3">
<h4><a href="{% url 'services:single' pk=post.id %}">{{ post.title }}</a></h4>
<p>{{ post.content|truncatewords_html:45|safe }}</p>
<a class="read-more-btn" href="{% url 'services:single' pk=post.id %}">بیشتر بدانید</a>
</div>
</div>
</div>
{% endfor %}
</div>
</div>
</div>


{% endblock content %}