blog/urls.py
from django.urls import path
from .views import HomeView, BlogListView, BlogDetailView, BlogSearchView
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='index'),
    path('blog/<str:cat_name>/', BlogListView.as_view(), name='blog_list_category'),
    path('blog/<str:username>/', BlogListView.as_view(), name='blog_list_author'),
    path('blog/tag/<str:tag_name>/', BlogListView.as_view(), name='tag'),

    # Define URL pattern for the blog detail page with post ID parameter
    path('<int:pk>/', BlogDetailView.as_view(), name='single'),

    # Define URL pattern for the blog search page
    path('search/', BlogSearchView.as_view(), name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog":BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('services/', include('services.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.handler404'

website/urls.py
from django.urls import path
from .views import *

app_name = 'website'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contactus/', ContactUsView.as_view(), name='contactus'),
    path('newslettersignup/', NewsletterView.as_view(), name='newsletter'),
    path('search/', IndexSearchView.as_view(), name='search'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from django_jalali.db import models as jmodels
from ckeditor.fields import RichTextField

class Category(models.Model):
    name = models.CharField("نام", max_length=31)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

class Post(models.Model):
    title = models.CharField("عنوان", max_length=255)
    content = RichTextField("محتوا")
    tags = TaggableManager("برچسب‌ها")
    published_date = jmodels.jDateField("تاریخ انتشار", null=True)
    status = models.BooleanField("نمایش در سایت", default=True)
    created_date = jmodels.jDateField("تاریخ ایجاد", auto_now_add=True)
    updated_date = jmodels.jDateField("تاریخ بروزرسانی", auto_now=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="نویسنده")
    counted_views = models.IntegerField("تعداد بازدیدها", default=0)
    counted_comment = models.IntegerField("تعداد نظرات", default=0)
    category = models.ManyToManyField(Category, verbose_name="دسته‌بندی")
    image = models.ImageField("تصویر", upload_to='post_images/') 

    class Meta:
        ordering = ['-created_date']
        verbose_name = "پست"
        verbose_name_plural = "پست‌ها"

    def __str__(self):
        return "{}-{}".format(self.title, self.id)
    
    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="پست")
    name = models.CharField("نام", max_length=100)
    email = models.EmailField("ایمیل")
    phone_number = models.CharField("شماره تلفن", max_length=200)
    message = models.TextField("پیام")
    approved = models.BooleanField("تایید شده", default=False)
    created_date = models.DateTimeField("تاریخ ایجاد", auto_now_add=True)
    updated_date = models.DateTimeField("تاریخ بروزرسانی", auto_now=True)

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"

    def __str__(self):
        return f'{self.name} - {self.phone_number}'

blog/forms.py
from django import forms
from .models import Comment  # Import the Comment model from your models.py

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # Specify the model to use for the form
        fields = ['name', 'email', 'phone_number', 'message']  # Define the fields to include in the for

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, View
from django.contrib import messages
from django.utils import timezone
from .models import Post
from .forms import CommentForm
from .query_manager import PostQueryManager, CommentQueryManager

class HomeView(View):
    template_name = 'blog/blog-home.html'

    def get(self, request):
        return render(request, self.template_name)

class BlogListView(ListView):
    template_name = 'blog/blog-home.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        current_time = timezone.now()
        queryset = PostQueryManager.get_all_posts()

        cat_name = self.kwargs.get('cat_name')
        if cat_name:
            queryset = PostQueryManager.get_posts_by_category(cat_name)

        username = self.kwargs.get('username')
        if username:
            queryset = PostQueryManager.get_posts_by_author(username)

        tag_name = self.kwargs.get('tag_name')
        if tag_name:
            queryset = PostQueryManager.get_posts_by_tag(tag_name)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for post in context['posts']:
            post.tags = post.tags.all()
        return context

class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/blog-single.html'
    context_object_name = 'post'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_time = timezone.now()
        all_posts = PostQueryManager.get_all_posts()
        current_index = list(all_posts).index(self.object)
        context['previous_post'] = all_posts[current_index - 1] if current_index > 0 else None
        context['next_post'] = all_posts[current_index + 1] if current_index < len(all_posts) - 1 else None
        context['comments'] = CommentQueryManager.get_comments_for_post(self.object)
        context['comment_form'] = CommentForm(initial=self.get_initial_data())
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.save()
        messages.success(self.request, 'ثبت با موفقیت انجام شد')
        return redirect(self.request.path_info)

    def form_invalid(self, form):
        messages.error(self.request, 'در ثبت فرم خطایی رخ داده است')
        return self.render_to_response(self.get_context_data(form=form))

    def get_initial_data(self):
        initial_data = {}
        if self.request.user.is_authenticated:
            initial_data['name'] = self.request.user.username
            initial_data['email'] = self.request.user.email
        return initial_data

class BlogSearchView(ListView):
    template_name = 'blog/blog-home.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('s')
        return PostQueryManager.search_posts(query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('s', '')
        return context

templates/blog/blog-categories.html
<div class="sidebar-card categories mt-30">
    <h3>دسته بندی ها</h3>
    <ul>
    {% for name, count in categories.items %}
    
    <li><a  href="{% url 'blog:blog_list_category' cat_name=name %}"><i class="fas fa-angle-double-left"></i>{{ name }} ({{ count }}) </a></li>
    {% endfor %}
    </ul>
    </div>

templates/blog/blog-comments.html
{% load static %}
{% load humanize %}

<div class="bd-comments details-text-area">
    <h3>نظرات</h3>
    {% for comment in comments %}
    <div class="comment-card">
    <img src="{% static 'assets/images/testimonial/tc1.jpg' %}" alt="image">
    <h5>{{ comment.name }}</h5>
    <p>{{ comment.message }}</p>
    <span class="date">{{ comment.created_date|naturalday }}</span>
    <!-- <a href="#bd-form">پاسخ</a> -->
    </div>
    {% endfor %}
    </div>

templates/blog/blog-home.html
{% extends 'base.html' %}

{% load static %}
{% load blog_tags %}

{% block content %}

<div class="uni-banner">
<div class="container">
<div class="uni-banner-text">
<h1>وبلاگ </h1>
<ul>
<li><a href="{% url 'website:index' %}">خانه</a></li>
<li>وبلاگ</li>
</ul>
</div>
</div>
</div>


<div class="blog pt-100">
<div class="container">
<div class="default-section-title default-section-title-middle">
<h6>وبلاگ</h6>
<h3>اخبار وبلاگ ما</h3>
</div>
<div class="section-content">
<div class="row justify-content-center">
{% for post in posts %}
<div class="col-lg-4 col-md-6 col-sm-12 col-12">
<div class="blog-card">
<div class="blog-card-img">
<a href="{% url 'blog:single' pk=post.id %}"><img src="{{ post.image.url }}" alt="{{ post.title }}"></a>
<a class="blog-card-category" href="{% url 'blog:single' pk=post.id %}">نظافت</a>
</div>
<div class="blog-card-text">
<div class="blog-date">
<ul>
<li><i class="far fa-user"></i> توسط {{post.author}}</li>
<li><i class="far fa-comments"></i>نظرات ({% comment_count post.id%})</li>
<li><i class="far fa-calendar-alt"></i> {{post.published_date|date:"D M Y"}} </li>
</ul>
</div>
<h4><a href="{% url 'blog:single' pk=post.id %}">{{post.title}}</a></h4>
<p>{{ post.content|truncatewords_html:45|safe }}</p>
<a class="read-more-btn" href="{% url 'blog:single' pk=post.id %}">بیشتر بخوانید</a>
</div>
</div>
</div>
{% endfor %}

<div class="pagination mt-60 d-flex justify-content-center">
    <ul class="pagination">
        <li>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number  }}"><i class="fas fa-arrow-right"></i></a>
            {% else %}
            {% endif %}
        </li>
        {% for i in page_obj.paginator.page_range %}
        {% if i >= page_obj.number|add:"-3" and i <= page_obj.number|add:"3" %}
            <li class="{% if i == page_obj.number %}active{% endif %}">
                <a href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
        {% endfor %}
    
        <li>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number  }}"><i class="fas fa-arrow-left"></i></a>
            {% else %}
            {% endif %}
        </li>
    </ul>
</div>

</div>
</div>
</div>


{% endblock content %}

templates/blog/blog-hours.html
<div class="sidebar-card mt-30 opening-card">
    <h3>ساعت کاری</h3>
    <ul>
    <li><span>شنبه-دوشنبه</span> <span>2:00صبح - 5:00شب</span></li>
    <li><span>جمعه-شنبه</span> <span>2:00صبح - 3:00شب</span></li>
    <li><span>یکشنبه</span> <span>بسته</span></li>
    </ul>
    </div>

templates/blog/blog-recent-posts.html
{% load static %}
<div class="sidebar-card recent-news">
    <h3>پست های اخیر</h3>
    {% for post in posts %}
    <div class="recent-news-card">
    <img src="{{ post.image.url }}" alt="{{ post.title }}">
    <h5><a href="{% url 'blog:single' pk=post.id %}">{{ post.title }}</a></h5>
    <p>{{post.published_date|date:"D M Y"}}</p>
    </div>
    {% endfor %}

    </div>

templates/blog/blog-search.html
<div class="sidebar-card search-box">
    <form action="{% url 'blog:search' %}">
    <div class="input-group">
    <!-- <input type="text" class="form-control" placeholder="جستجو..." required> -->
    <input type="text" class="form-control" name="s" placeholder="جستجو..." required>
    <button class="btn" type="submit"><i class="fas fa-search"></i></button>
    </div>
    </form>
    </div>

templates/blog/blog-send-comment.html
{% load static %}
<div class="bd-form details-text-area bg-f9faff" id="bd-form">
    <h3>نظر دهید</h3>
    <form method="post">
        {% csrf_token %}
        {{ comment_form.errors }}
    <div class="row">
    <div class="col-md-6">
    <input type="text" class="form-control" name="name" placeholder="نام" required>
    </div>
    <div class="col-md-6">
    <input type="email" class="form-control" name="email"  placeholder="ایمیل" required>
    </div>
    <div class="col-md-6">
    <input type="text" class="form-control" name="phone_number" placeholder="تلفن" required>
    </div>
    <div class="col-md-12">
    <textarea rows="5" class="form-control" name="message" placeholder="پیام شما" required></textarea>
    </div>
    <div class="col-md-12">
    <button class="default-button" type="submit"><span>ارسال</span></button>
    </div>
    </div>
    </form>
    </div>

templates/blog/blog-single.html
{% extends 'base.html' %}

{% load static %}
{% load blog_tags %}


{% block content %}

<div class="uni-banner">
<div class="container">
<div class="uni-banner-text">
<h1>{{post.title}}</h1>
<ul>
<li><a href="{% url 'website:index' %}">خانه</a></li>
<li>{{post.title}}</li>
</ul>
</div>
</div>
</div>


<div class="blog ptb-100">
<div class="container">
<div class="row">
<div class="col-lg-8 col-md-12 col-sm-12 col-12">
<div class="blog-details-text-area pr-20">
<div class="blog-card mt-0">
<div class="blog-card-img">
<a href="{% url 'blog:single' pk=post.id %}"><img src="{{ post.image.url }}" alt="image"></a>
<a class="blog-card-category" href="blog-details.html">خدمات نظافت</a>
</div>
<div class="blog-card-text">
<div class="blog-date">
<ul>
<li><i class="far fa-user"></i> توسط {{post.author}}</li>
<li><i class="far fa-comments"></i> نظرات  ({% comment_count post.id%}) </li>
<li><i class="far fa-calendar-alt"></i> 21 دی 1400</li>
</ul>
</div>
<h4>{{post.title}}</h4>
<p>{{post.content|safe}}</p>
</div>
</div>
<div class="blog-text-footer">
<div class="tag-area">
<ul>
<li><i class="fas fa-tags"></i></li>
{% for category in post.category.all %}
  {% if not forloop.last %}
    <li>{{ category }} , </li>
  {% else %}
    <li>{{ category }}</li>
  {% endif %}
{% endfor %}
</ul>
</div>
<!-- <div class="social-icons">
<ul>
<li><span>اشتراک گذاری:</span></li>
<li><a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
<li><a href="https://www.linkedin.com/" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
<li><a href="https://twitter.com/" target="_blank"><i class="fab fa-twitter"></i></a></li>
<li><a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram"></i></a></li>
</ul>
</div> -->
</div>

{% include 'blog/blog-comments.html' %}
{% include 'blog/blog-send-comment.html' %}

</div>
</div>
<div class="col-lg-4 col-md-12 col-sm-12 col-12">
<div class="sidebar-content pt-30">
{% include 'blog/blog-search.html' %}
{% postcategories %}
{% popularposts %}
<div class="sidebar-card sd-tag">
<h3>برچسب ها</h3>
<ul>
{% for tag in post.tags.all %}
<li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
{% endfor %}

</ul>
</div>
<!-- {% include 'blog/blog-hours.html' %} -->
</div>
</div>
</div>
</div>
</div>
{% endblock content %}